<?php

namespace EO\ETicketBundle\Repository;

/**
 * AvailableDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvailableDateRepository extends \Doctrine\ORM\EntityRepository
{
}
