<?php

namespace EO\ETicketBundle\Repository;

/**
 * MuseumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuseumRepository extends \Doctrine\ORM\EntityRepository
{
}
