<?php
/**
 * Created by PhpStorm.
 * User: belou
 * Date: 30/10/17
 * Time: 22:14
 */

namespace EO\ETicketBundle\Form;

use EO\ETicketBundle\Enum\BookingEnum;
use EO\ETicketBundle\Type\BookingType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Choice;

class BookingChoiceType extends AbstractType
{
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'choices' => BookingType::getValues(),
            'data' => BookingEnum::FULL,
            'multiple' => false,
            'expanded' => true,
            'invalid_message' => "{{ value }} n'est pas un type de réservation reconnu"
            )
        );
    }

    public function  buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getParent()
    {
        return ChoiceType::class;
    }

    public function getBlockPrefix()
    {
        return 'bookingchoice';
    }
}