<?php
/**
 * Created by PhpStorm.
 * User: belou
 * Date: 20/10/17
 * Time: 16:55
 */

namespace EO\ETicketBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DatePickerType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
                'widget' => 'single_text',
                'format' => 'dd/MM/yyyy',
                'attr' => array('class' => 'date-picker')
            )
        );
    }

    public function getParent()
    {
        return DateType::class; // TODO: Change the autogenerated stub
    }

    public function getName()
    {
        return 'datepicker';
    }
}