eoe_ticket_homepage:
    path:     /
    defaults: { _controller: EOETicketBundle:Home:index }

eoe_ticket_available:
    path: /availableDate
    defaults: { _controller: EOETicketBundle:Home:date }

eoe_ticket_addticket:
    path: /add
    defaults: { _controller: EOETicketBundle:Home:add }

eoe_ticket_loadrates:
    path: /load
    defaults: { _controller: EOETicketBundle:Home:load }