eoe_ticket_homepage:
    path:     /
    defaults: { _controller: EOETicketBundle:Home:index }

eoe_ticket_available:
    path: /availableDate
    defaults: { _controller: EOETicketBundle:Home:date }

eoe_ticket_addticket:
    path: /add
    defaults: { _controller: EOETicketBundle:Home:add }

eoe_ticket_loadrates:
    path: /load
    defaults: { _controller: EOETicketBundle:Home:load }

eoe_ticket_paiement:
    path: /payment
    defaults: { _controller: EOETicketBundle:Payment:index }

eoe_ticket_charge:
  path: /charge
  defaults: { _controller: EOETicketBundle:Payment:charge }

eoe_ticket_succeed:
  path: /confirmation
  defaults: { _controller: EOETicketBundle:Payment:succeed }

eoe_ticket_failure:
  path: /failure
  defaults: { _controller: EOETicketBundle:Payment:failure }