services:
    form.type.datePicker:
      class: EO\ETicketBundle\Form\DatePickerType
      tags:
        - { name: form.type, alias: datePicker }


#    eoe_ticket.example:
#        class: EO\ETicketBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
