services:
    form.type.datepicker:
        class: EO\ETicketBundle\Form\DatePickerType
        tags:
          - { name: form.type, alias: datepicker }

    form.type.bookingchoice:
        class: EO\ETicketBundle\Form\BookingChoiceType
        tags:
          - {name: form.type, alias: bookingchoice }

    form.type.ticket:
        class: EO\ETicketBundle\Form\TicketType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - { name: form.type }

    form.type.booking:
          class: EO\ETicketBundle\Form\BookingType
          arguments: ["@doctrine.orm.entity_manager"]
          tags:
            - { name: form.type }

    eo_eticket.validator.notavailableplace:
      class: EO\ETicketBundle\Validator\NotAvailablePlaceValidator
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
        - { name: validator.constraint_validator, alias: eo_eticket_notvailableplace }

    eo_eticket.bookingmailer:
      class: EO\ETicketBundle\BookingMailer\EOBookingMailer
      arguments: ["@mailer","@templating", "@doctrine.orm.entity_manager"]

#    eoe_ticket.example:
#        class: EO\ETicketBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
